# Generated by Django 4.2.16 on 2025-03-17 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people_management", "0003_person_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The associated Django user account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
