# Generated by Django 4.2.16 on 2025-03-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0003_rename_person_id_contract_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='people_management.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
