# Generated by Django 4.2.16 on 2025-03-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0004_alter_contract_person_alter_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='people_management.person'),
        ),
    ]
