# Generated by Django 4.2.16 on 2025-03-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people_management", "0005_historicalperson_historicalcontract"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historicalcontract",
            table="contract_history",
        ),
        migrations.AlterModelTable(
            name="historicalperson",
            table="person_history",
        ),
    ]
