# Generated by Django 4.2.16 on 2025-03-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0006_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr_admin', 'HR Admin')], default='employee', max_length=20),
        ),
    ]
