# Generated by Django 4.2.16 on 2025-03-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR Admin', 'HR Admin')], max_length=50, unique=True),
        ),
    ]
