# Generated by Django 4.2.16 on 2025-03-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_assign_default_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
